Authentication of API endpoints
Leyline-gg/pog-api pull request #31
Opened 2022-04-28 20:38 UTC by elijaholmos

## known issues
`AuthRepository.findOne()` with an `apikey` filter appears to be behaving improperly. Note the below screenshot of code & console output:
![image](https://user-images.githubusercontent.com/35435704/165841131-ca0f47f3-fd33-4e6c-b20f-edf74a7a6775.png)
the API token being passed in the header and sent to the method is `ab4a8890-c402-11ec-86a1-717d96b2a455`
the object assigned to variable `f` is correctly constructed with the above api key
this object is passed as the filter into `authRepository.findOne()`. I have ensured that there is a document in the `oracleapikey` collection with an `apikey` field that exactly matches the `token` variable
despite this, the `findOne()` method is returning a completely different `OracleApiKey`, as shown in the console

2022-04-29 00:35 UTC, kharaone commented
@elijaholmos I will need some help in order to reproduce your error and setup the whole api with auth

2022-04-30 14:07 UTC, kharaone commented
@elijaholmos ok, it seems the error is tied to the connector : 
it's using `Object.prototype.hasOwnProperty.call(where, 'key')` but it's incorrectly setting the property name, instead of using the value contained in the variable, it's using the string name of the variable.
if I switch the `Object.prototype.hasOwnProperty.call(where, 'key')` to `Object.prototype.hasOwnProperty.call(where, key)` on line 460 of `src\connectors\BetterFirestoreConnector.ts` I'm getting through correctly.

2022-04-30 14:08 UTC, kharaone requested changes
see previous comment

2022-04-30 20:08 UTC, elijaholmos commented
@kharaone I verified that your proposed solution fixed the bug - thank you for helping me solve it

2022-05-01 21:02 UTC, kharaone requested changes
Here are a few suggestions on how to proceed further

2022-05-01 21:02 UTC, kharaone commented on src/sequence.ts
> +export class MySequence implements SequenceHandler {
I would have mentioned the fact that the middleware route seemed to be the correct way to go, but seeing you removed the ` extends MiddlewareSequence` makes me wonder why you chose to go back to the sequenceHandler ?

2022-05-01 21:02 UTC, kharaone commented on src/sequence.ts
> +      if (route.pathParams.id != oracle.id) throw new AuthError(403);
This part is specific to /oracle endpoint and will need to be constrained accordingly. Moreover, it feels more like authorization than authentication, you will need to find a better place to define these rules

2022-05-01 21:02 UTC, kharaone commented on src/sequence.ts
> +      if (oracle === undefined) return next();
needs to be awaited

2022-05-01 21:02 UTC, kharaone commented on src/sequence.ts
> +      if (oracle.id == 0) return next(); // SYSTEM account
needs to be awaited

2022-05-01 21:02 UTC, kharaone commented on src/sequence.ts
> +        throw new AuthError(403);
if if's not a one liner, put the {} around the if scope

2022-05-01 21:02 UTC, kharaone commented on src/providers/verifyFn.provider.ts
> +        };
Shouldn't we have a check on expired too ?

2022-05-01 21:02 UTC, kharaone commented on src/providers/verifyFn.provider.ts
> +      console.log('in value! token:', token);
to be removed

2022-05-01 21:02 UTC, kharaone commented on src/providers/verifyFn.provider.ts
> +        console.log(f);
to be removed

2022-05-01 21:02 UTC, kharaone commented on src/providers/verifyFn.provider.ts
> +        console.log(oracleApiKey);
to be removed

2022-05-01 21:02 UTC, kharaone commented on src/providers/verifyFn.provider.ts
> +          throw new AuthError(401);
if not a oneliner, please encapsulate with `{}`

2022-05-01 21:02 UTC, kharaone commented on src/oracleprofile.factory.ts
> +  return {...oracle, [securityId]: oracle?.id?.toString() || ''} as GoodOracle;
```suggestion
  return {...oracle, [securityId]: oracle?.id?.toString() ?? ''} as GoodOracle;
```

2022-05-01 21:02 UTC, kharaone commented on src/oracleprofile.factory.ts
> +export const OracleProfileFactory: UserProfileFactory<GoodOracle> = function (
I'd move that file it in models

2022-05-01 21:02 UTC, kharaone commented on src/models/good-oracle.model.ts
> +  [securityId]: string = this.id?.toString() || '';
```suggestion
  [securityId]: string = this.id?.toString() ?? '';
```

2022-05-01 21:02 UTC, kharaone commented on src/providers/auth-error.ts
> +export default class AuthError extends Error {
agreed, this should be translated into an errorresponse either through an interceptor or a middleware

2022-05-01 21:02 UTC, kharaone commented on src/providers/passport-bearer-auth.ts
> +export class PassportBearerAuthProvider<GoodOracle>
should probably contain `provider `in the filename to stay consistent in the naming convention

2022-05-03 16:24 UTC, kharaone approved these changes
I'm still concerned of the part in sequence.ts which seemed specific to /oracle endpoint. You should at least guard the section with a conditional on the url 

if url === /oracle then apply rules.

2022-05-03 16:39 UTC, elijaholmos commented
@kharaone sorry, that was only the first part 😅 I'll re-request review once I'm finished with all the suggested changes

2022-05-03 16:45 UTC, elijaholmos commented on src/sequence.ts
> +export class MySequence implements SequenceHandler {
It was largely motivated by lb4's example found at https://github.com/loopbackio/loopback-next/blob/e2ff6b22367e919926d0f41f6d939d988c654c00/examples/todo-jwt/src/sequence.ts

2022-05-03 17:43 UTC, elijaholmos commented on src/sequence.ts
> +      if (route.pathParams.id != oracle.id) throw new AuthError(403);
refactored in 8e71216344520cba30854a9c3ded48664ded42bd

2022-05-03 17:49 UTC, elijaholmos commented
@kharaone two final questions:
1. for the sake of PR scope, could a separate story be created for the handling & displaying of API errors to the requester? including converting `AuthError`s into `ErrorResponse`s?
2. would you like me to implement authentication on the remaining endpoints before merging this? `/activity`, `/entry`, etc

2022-05-03 17:52 UTC, kharaone commented
@elijaholmos 
1. sure, we can implement that in another story indeed
2. you should avoid /entry for now as @gitluky is getting that part overhauled. Feel free to either create separate stories for each endpoints or implement these in that PR

2022-05-03 17:53 UTC, elijaholmos commented
@kharaone thank you, I will go ahead and move everything to separate stories so this can be merged once re-approved

2022-05-04 16:52 UTC, kharaone approved these changes
- I didn't update the tests with the authentication dimension (as there's apparently no way to insert an ID = 0 in the datasource, so we'll need to change the admin flag to be an actual flag)
- any person calling /auth with oracleId = X can "override" its apikey ... feels a bit problematic. We will probably need to do secret ids or even jwt token flow instead.

2022-05-04 17:08 UTC, elijaholmos commented
I have a few ideas about the second point, for discussion at a future sync

2022-05-04 17:26 UTC, merged