create ProofOfGoodEntry endpoint
Leyline-gg/pog-api pull request #4
Opened 2022-03-29 04:34 UTC by elijaholmos

2022-03-29 05:44 UTC, elijaholmos commented
removed `src\controllers\open-api.controller.ts` because of a jsonschema error
![image](https://user-images.githubusercontent.com/35435704/160541573-a422bc4e-07f7-49b3-952d-781fc78c3ef7.png)

2022-03-29 19:38 UTC, kharaone requested changes
Looks good as a whole.

I have a few changes requests in order to align with the excel document AND be consistent

2022-03-29 19:38 UTC, kharaone commented on src/repositories/index.ts
> +export * from './proof-of-good-entry.repository';
small comment on naming convention. Should we rename `proof-of-good-entry` into `good-entry`

2022-03-29 19:38 UTC, kharaone commented on src/models/index.ts
> +export * from './proof-of-good-entry.model';
naming convention consistency, should we rename these into `good-entry` and `good-entry-input` ?

2022-03-29 19:38 UTC, kharaone commented on src/models/good-category.model.ts
> +      type: 'string',
Probably better to have it decorated as an integer

```suggestion
      type: 'number',
```

2022-03-29 19:38 UTC, kharaone commented on src/controllers/category.controller.ts
> +      if (err.message == '404')
```suggestion
      if (err.message == 'Document not found')
```
to stay consistent with the error handling of BetterFirestoreConnector

2022-03-29 19:38 UTC, kharaone commented on src/controllers/activity.controller.ts
> +      if (err.message == '404')
```suggestion
      if (err.message == 'Document not found')
```

2022-03-29 19:38 UTC, kharaone commented on src/controllers/activity.controller.ts
> +      if (err.message == '404')
which means L169 of src\connectors\BetterFirestoreConnector.ts needs to be changed

2022-03-29 22:35 UTC, elijaholmos commented on src/models/index.ts
> +export * from './proof-of-good-entry.model';
no objection from me

2022-03-29 22:41 UTC, elijaholmos commented on src/repositories/index.ts
> +export * from './proof-of-good-entry.repository';
resolved w 90d258a2744c1efa285c8932754c5b5b2203cee9

2022-03-29 22:41 UTC, elijaholmos commented on src/models/index.ts
> +export * from './proof-of-good-entry.model';
resolved w 90d258a2744c1efa285c8932754c5b5b2203cee9

2022-03-30 10:21 UTC, kharaone requested changes
Looks Good To Me

Just an oversight on the error message to be corrected, and we're good :)

2022-03-30 10:21 UTC, kharaone commented on src/controllers/category.controller.ts
>          throw new HttpErrors.NotFound('Oracle Not Found');
```suggestion
        throw new HttpErrors.NotFound('Category Not Found');
```

2022-03-30 14:52 UTC, merged